### ISSUE TITLE
Build problems under Ubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by DanielTBrown** [vsimon/webrtcbuilds#14]
build.sh generates an error after running for approximately 35 minutes, shortly after completing the git checkout.

The operating system is Ubuntu 16.04 64-bit running on AMD.

The error report from the console is (to make it easier to read, I have replaced my path to the webrtcbuilds directory with '...', the replaced path is approximately 46 characters long):

________ running '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '.../webrtcbuilds/out/src/chromium'
Error: Command '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in .../webrtcbuilds/out/src/chromium
Installing Debian Wheezy amd64 root image: .../webrtcbuilds/out/src/chromium/src/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c09e94d74f6efc174bd88195eee902b4350fc006/debian_wheezy_amd64_sysroot.tgz
Traceback (most recent call last):
  File "src/build/linux/sysroot_scripts/install-sysroot.py", line 232, in <module>
    sys.exit(main(sys.argv[1:]))
  File "src/build/linux/sysroot_scripts/install-sysroot.py", line 153, in main
    InstallDefaultSysroots()
  File "src/build/linux/sysroot_scripts/install-sysroot.py", line 127, in InstallDefaultSysroots
    InstallSysroot(host_arch)
  File "src/build/linux/sysroot_scripts/install-sysroot.py", line 218, in InstallSysroot
    ['curl', '--fail', '--retry', '3', '-L', url, '-o', tarball])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python -u src/sync_chromium.py --target-revision 938114be1ecffa98a68ededc466b85ab6b16dcd8' returned non-zero exit status 2 in .../webrtcbuilds/out

**Comment by vsimon** [comment]
I see there are no project files generated, which would be generated in out/Debug/..., out/Release/... folders for example.

Perhaps previously the `gclient runhooks` command took care of generating project files and now since the development guide says `fetch --nohooks webrtc`, this would no longer work (I'm guessing from --nohooks).
The development guide recommends `python webrtc/build/gyp_webrtc.py` to generate project files for gyp. Just changing `gclient runhooks` to that for all platforms may be the immediate solution.

**Comment by vsimon** [comment]
Testing python webrtc/build/gyp_webrtc.py on Ubuntu 16.04

**Comment by DanielTBrown** [comment]
Would this solution also eliminate the reference $WIN_DEPOT_TOOLS under Microsoft Windows? Presumably this would replace:

cmd //c "$WIN_DEPOT_TOOLS\gclient.bat runhooks"

with:

python webrtc/build/gyp_webrtc.py

**Comment by vsimon** [comment]
Yes I believe it would.

**Comment by DanielTBrown** [comment]
Unfortunately the Ubuntu 16.04 build fails for me, even with the change to:

python webrtc/build/gyp_webrtc.py

The error messages are the same as previously.

**Comment by vsimon** [comment]
Sorry, that I copy pasted from the webrtc development guide, in the context of the build it would be:

```
diff --git a/util.sh b/util.sh
index a43553d..1c9c6776 100644
--- a/util.sh
+++ b/util.sh
@@ -189,7 +189,7 @@ function compile() {
     # do the build
     configs="Debug Release"
     for cfg in $configs; do
-      gclient runhooks
+      python src/webrtc/build/gyp_webrtc.py
       ninja -C src/out/$cfg
       # combine all the static libraries into one called webrtc_full
       pushd src/out/$cfg
```

Still out for test on 16.04. Will have a result shortly.

**Comment by vsimon** [comment]
Compile works. Pull request coming. Unable to test Windows at the moment so I'll open an issue for that.

**Comment by vsimon** [comment]
https://github.com/vsimon/webrtcbuilds/issues/9 can track this.

**Comment by DanielTBrown** [comment]
Even with the change to python src/webrtc/build/gyp_webrtc.py, the Ubuntu 16.04 build still fails for me in the same manner. There must be something going on in addition to the other problems.

**Comment by vsimon** [comment]
Same error as the original report?

`line 218, in InstallSysroot
['curl', '--fail', '--retry', '3', '-L', url, '-o', tarball])` 
Could this curl be failing?
i.e.
`curl -O https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c09e94d74f6efc174bd88195eee902b4350fc006/debian_wheezy_i386_sysroot.tgz`

Comparing it an output from a latest build, not sure why it might be failing.

```
Installing Debian Wheezy amd64 root image: /builds/webrtcbuilds/out/src/chromium/src/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c09e94d74f6efc174bd88195eee902b4350fc006/debian_wheezy_amd64_sysroot.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  7 41.6M    7 3232k    0     0  3506k      0  0:00:12 --:--:--  0:00:12 3505k
 49 41.6M   49 20.6M    0     0  10.7M      0  0:00:03  0:00:01  0:00:02 10.7M
 84 41.6M   84 35.0M    0     0  12.0M      0  0:00:03  0:00:02  0:00:01 12.0M
100 41.6M  100 41.6M    0     0  12.5M      0  0:00:03  0:00:03 --:--:-- 12.5M
Installing Debian Wheezy i386 root image: /builds/webrtcbuilds/out/src/chromium/src/build/linux/debian_wheezy_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c09e94d74f6efc174bd88195eee902b4350fc006/debian_wheezy_i386_sysroot.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 18 44.6M   18 8575k    0     0  9378k      0  0:00:04 --:--:--  0:00:04 9371k
 53 44.6M   53 23.6M    0     0  12.3M      0  0:00:03  0:00:01  0:00:02 12.3M
 91 44.6M   91 40.7M    0     0  13.9M      0  0:00:03  0:00:02  0:00:01 13.9M
100 44.6M  100 44.6M    0     0  14.3M      0  0:00:03  0:00:03 --:--:-- 14.3M
Hook '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 10.12 secs

________ running '/usr/bin/python src/build/vs_toolchain.py update' in '/builds/webrtcbuilds/out/src/chromium'

________ running '/usr/bin/python src/build/mac_toolchain.py' in '/builds/webrtcbuilds/out/src/chromium'
```

**Comment by DanielTBrown** [comment]
Yes, same error as the original report. I verified that the target directory for the curl exists, as well as the tarball source. I'm seeing what I can find.

**Comment by vsimon** [comment]
Long shot, I have seen google auto-limiting downloads to my IP for a cool-off period after building webrtc a large number of times in one day. Hence I was curious what curling that URL directly would say.

**Comment by DanielTBrown** [comment]
I found the problem - very stupid. curl was not installed. Apparently, it is not included by default in Ubuntu 16.04.

**Comment by vsimon** [comment]
Great to hear.

But check::deps should have included it, shouldn't it? It is the first item in the list of packages.

**Comment by DanielTBrown** [comment]
curl is the first item in the list of packages, I do not know why it was not loaded. I manually checked many of the other packages, and found none missing.

**Comment by vsimon** [comment]
You're totally right. dpkg-query needs tweaking/replacing to better check packages are installed.

**Comment by vsimon** [comment]
Just `dpkg -s` does the trick.

**Comment by vsimon** [comment]
Closing the loop on this one with https://github.com/vsimon/webrtcbuilds/pull/17
