### ISSUE TITLE
Build problems on OSX

### ISSUE THREAD

**Issue by vsimon** [vsimon/webrtcbuilds#15]
1. checking for the absence of variable via -v MSVSVER does not work with the 'nounset' option on non-windows platforms.
2. readlink on osx does not have an -f option.

**Comment by DanielTBrown** [comment]
Regarding -v MSVSVER, I see my mistake. With 'nounset' set, a way that should work is:

if [ -n "${MSVSVER:-}" ]; then

I am testing.

**Comment by vsimon** [comment]
For readlink, just wanted an absolute path. `OUTDIR=$(cd $OUTDIR && pwd -P)` may suffice (OSX, linux works I think that would also work on Windows).

**Comment by DanielTBrown** [comment]
A reasonable solution for the -v MSVSVER problem that works is:

MSVSVER=${MSVSVER:-}
if [ -n MSVSVER ]; then
  export GYP_MSVS_VERSION=$MSVSVER
fi

I will create a pull request.

**Comment by vsimon** [comment]
Looks good.

Just tested it and the conditional always hit on OSX, due to the missing $ var reference, -n tests for a not-zero length string...perhaps something like this?

if [ -n "$MSVSVER" ]; then
  export GYP_MSVS_VERSION=$MSVSVER
fi

**Comment by DanielTBrown** [comment]
I am testing your solution (-n "$MSVSVER") under Ubuntu, which is all I have this afternoon. It seems to work so far.

**Comment by vsimon** [comment]
Great, thank you!

**Comment by DanielTBrown** [comment]
The solution -n "$MSVSVER" works under Ubuntu 16.04.

**Comment by vsimon** [comment]
With https://github.com/vsimon/webrtcbuilds/pull/19 merged, good to close.
