### ISSUE TITLE
how to compile webrtc？

### ISSUE THREAD

**Issue by harvestsure** [vsimon/webrtcbuilds#4]
can u tell me how to compile webrtc？ I've tried countless times for several months, but I failed..   I follow the official instructions, I've tried njnia or vs2013... there were various problems. :( 
i need linux32 too,so that i can work with andorid device.i just want android device communicate to pc(both linux and windows).

there is my email  admin@gupar.com, thank you sooooooooooooo much!!!

**Comment by vsimon** [comment]
Hi gupar,
Yes I know compiling webrtc is not a straightforward task. I'm going create another repo sharing my scripts on how currently webrtcbuilds gets built. I think that would be a good place to start. (and you might also want to extend as you need linux32 too).  I'll update once I have the repo up.

**Comment by vsimon** [comment]
Here it is: https://github.com/vsimon/webrtcbuilds-builder
