### ISSUE TITLE
Build problems under Microsoft Windows

### ISSUE THREAD

**Issue by DanielTBrown** [vsimon/webrtcbuilds#9]
The Microsoft Windows build does not work for me. I have created a fork to fix the problems, and will post a pull request when done. If someone can provide a little help with a problem regarding depot_tools listed under 'Next problem', I would appreciate it.

Problems fixed so far:
- Platform detection (util.sh function set-platform): the (recommended) git bash shell returns an $OSTYPE value of 'msys' (mingw). Added detection of $OSTYPE 'msys', set PLATFORM to 'windows'.
- curl output directory creation (util.sh function check::deps): the 'curl' command to load jq.exe fails to create the output directory, even with --create-dirs specified. Added an explicit 'mkdir --parents', this fixed the problem.

Next problem:
- depot_tools, fetch command (util.sh function checkout): the 'fetch' command is not found. This may result from an interaction between util.sh functions check::depot-tools and check:deps. check::deps creates the depot_tools directory to load python276_bin/jq.exe, so check::depot-tools finds that the depot_tools directory already exists, and does not load the tools. I would appreciate any suggestions about how to fix the handling in a clean manner.

**Comment by DanielTBrown** [comment]
In build.sh, I reversed the call sequence, it is now 'check::depot_tools' followed by 'check::deps'. This allows the util.h 'check::depot-tools' call to 'git clone' to work.

Next problem:
- schtasks (in util.h check::depot-tools): the call to schtasks results in an error 'Access is denied', even from an administrative account. It seems unclear why 'schtasks' is used, why not invoke 'gclient.bat' directly?

**Comment by DanielTBrown** [comment]
I manually executed 'glient.bat', and it ran. I will replace the 'schtasks' call with a direct call to 'gclient.bat'.

Next problem:
- Although the documentation recommends Microsoft Visual Studio 2013 Community Edition, the python script 'landmines.py' reports the error 'Exception: Visual Studio Version 2015 (from GYP_MSVS_VERSION) not found.'

**Comment by DanielTBrown** [comment]
The Chromium build now defines to Microsoft Visual C++ 2015. For Microsoft Visual C++ 2013, it is necessary to set 'GYP_MSVS_VERSION' to '2013'.

**Comment by DanielTBrown** [comment]
Now I have a fork of build.sh/util.sh appear to run properly under Microsoft Windows, git bash shell, and Microsoft Visual C++ 2013. However, I see an error message:

sed: can't read .../out/src/webrtc/modules/video_render/windows/video_render_direct3d9.h: No such file or directory

The directory .../out/src/webrtc/modules contains no directory 'video_render'.

To help locating the error, the build.sh output three lines above this error is:

Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' took 725.08 secs

**Comment by vsimon** [comment]
Thanks Daniel, you're right the video render module looks to might be relocated, seeing if that might be the case. Other option is this is no longer needed.

**Comment by DanielTBrown** [comment]
Now that pull request #11 is merged, I am left with the following issues regarding building under Microsoft Windows:
- util.sh refers to $WIN_DEPOT_TOOLS, which does not exist. The build crashes. Any suggestions?
- util.sh has 'TODO' marked where I commented out references to non-existent files. Any suggestions about how to determine if this is a safe solution?

Thanks.

**Comment by vsimon** [comment]
- `$WIN_DEPOT_TOOLS\gclient.bat runhooks` should be migrated to `python src/webrtc/build/gyp_webrtc.py`

**Comment by DanielTBrown** [comment]
The problems should be fixed by pull request #18. I will mark this issue closed for now.
